CREATE TABLE blocks (
  name   TEXT(255) PRIMARY KEY,
  first  INTEGER(7),
  last   INTEGER(7),
  `type` TEXT(7)
);
CREATE INDEX cps ON blocks ( first, last );
CREATE INDEX `type` ON blocks ( `type` );

INSERT INTO blocks (name, first, last, `type`) VALUES ('Basic Latin', 0, 127, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Latin-1 Supplement', 128, 255, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Latin Extended-A', 256, 383, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Latin Extended-B', 384, 591, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('IPA Extensions', 592, 687, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Spacing Modifier Letters', 688, 767, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Combining Diacritical Marks', 768, 879, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Greek and Coptic', 880, 1023, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Cyrillic', 1024, 1279, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Cyrillic Supplement', 1280, 1327, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Armenian', 1328, 1423, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Hebrew', 1424, 1535, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Arabic', 1536, 1791, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Syriac', 1792, 1871, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Arabic Supplement', 1872, 1919, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Thaana', 1920, 1983, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('NKo', 1984, 2047, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Samaritan', 2048, 2111, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Devanagari', 2304, 2431, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Bengali', 2432, 2559, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Gurmukhi', 2560, 2687, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Gujarati', 2688, 2815, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Oriya', 2816, 2943, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Tamil', 2944, 3071, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Telugu', 3072, 3199, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Kannada', 3200, 3327, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Malayalam', 3328, 3455, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Sinhala', 3456, 3583, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Thai', 3584, 3711, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Lao', 3712, 3839, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Tibetan', 3840, 4095, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Myanmar', 4096, 4255, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Georgian', 4256, 4351, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Hangul Jamo', 4352, 4607, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Ethiopic', 4608, 4991, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Ethiopic Supplement', 4992, 5023, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Cherokee', 5024, 5119, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Unified Canadian Aboriginal Syllabics', 5120, 5759, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Ogham', 5760, 5791, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Runic', 5792, 5887, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Tagalog', 5888, 5919, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Hanunoo', 5920, 5951, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Buhid', 5952, 5983, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Tagbanwa', 5984, 6015, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Khmer', 6016, 6143, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Mongolian', 6144, 6319, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Unified Canadian Aboriginal Syllabics Extended', 6320, 6399, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Limbu', 6400, 6479, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Tai Le', 6480, 6527, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('New Tai Lue', 6528, 6623, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Khmer Symbols', 6624, 6655, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Buginese', 6656, 6687, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Tai Tham', 6688, 6831, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Balinese', 6912, 7039, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Sundanese', 7040, 7103, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Lepcha', 7168, 7247, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Ol Chiki', 7248, 7295, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Vedic Extensions', 7376, 7423, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Phonetic Extensions', 7424, 7551, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Phonetic Extensions Supplement', 7552, 7615, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Combining Diacritical Marks Supplement', 7616, 7679, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Latin Extended Additional', 7680, 7935, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Greek Extended', 7936, 8191, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('General Punctuation', 8192, 8303, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Superscripts and Subscripts', 8304, 8351, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Currency Symbols', 8352, 8399, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Combining Diacritical Marks for Symbols', 8400, 8447, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Letterlike Symbols', 8448, 8527, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Number Forms', 8528, 8591, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Arrows', 8592, 8703, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Mathematical Operators', 8704, 8959, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Miscellaneous Technical', 8960, 9215, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Control Pictures', 9216, 9279, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Optical Character Recognition', 9280, 9311, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Enclosed Alphanumerics', 9312, 9471, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Box Drawing', 9472, 9599, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Block Elements', 9600, 9631, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Geometric Shapes', 9632, 9727, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Miscellaneous Symbols', 9728, 9983, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Dingbats', 9984, 10175, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Miscellaneous Mathematical Symbols-A', 10176, 10223, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Supplemental Arrows-A', 10224, 10239, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Braille Patterns', 10240, 10495, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Supplemental Arrows-B', 10496, 10623, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Miscellaneous Mathematical Symbols-B', 10624, 10751, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Supplemental Mathematical Operators', 10752, 11007, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Miscellaneous Symbols and Arrows', 11008, 11263, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Glagolitic', 11264, 11359, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Latin Extended-C', 11360, 11391, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Coptic', 11392, 11519, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Georgian Supplement', 11520, 11567, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Tifinagh', 11568, 11647, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Ethiopic Extended', 11648, 11743, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Cyrillic Extended-A', 11744, 11775, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Supplemental Punctuation', 11776, 11903, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('CJK Radicals Supplement', 11904, 12031, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Kangxi Radicals', 12032, 12255, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Ideographic Description Characters', 12272, 12287, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('CJK Symbols and Punctuation', 12288, 12351, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Hiragana', 12352, 12447, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Katakana', 12448, 12543, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Bopomofo', 12544, 12591, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Hangul Compatibility Jamo', 12592, 12687, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Kanbun', 12688, 12703, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Bopomofo Extended', 12704, 12735, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('CJK Strokes', 12736, 12783, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Katakana Phonetic Extensions', 12784, 12799, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Enclosed CJK Letters and Months', 12800, 13055, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('CJK Compatibility', 13056, 13311, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('CJK Unified Ideographs Extension A', 13312, 19903, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Yijing Hexagram Symbols', 19904, 19967, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('CJK Unified Ideographs', 19968, 40959, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Yi Syllables', 40960, 42127, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Yi Radicals', 42128, 42191, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Lisu', 42192, 42239, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Vai', 42240, 42559, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Cyrillic Extended-B', 42560, 42655, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Bamum', 42656, 42751, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Modifier Tone Letters', 42752, 42783, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Latin Extended-D', 42784, 43007, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Syloti Nagri', 43008, 43055, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Common Indic Number Forms', 43056, 43071, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Phags-pa', 43072, 43135, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Saurashtra', 43136, 43231, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Devanagari Extended', 43232, 43263, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Kayah Li', 43264, 43311, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Rejang', 43312, 43359, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Hangul Jamo Extended-A', 43360, 43391, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Javanese', 43392, 43487, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Cham', 43520, 43615, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Myanmar Extended-A', 43616, 43647, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Tai Viet', 43648, 43743, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Meetei Mayek', 43968, 44031, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Hangul Syllables', 44032, 55215, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Hangul Jamo Extended-B', 55216, 55295, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('High Surrogates', 55296, 56191, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('High Private Use Surrogates', 56192, 56319, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Low Surrogates', 56320, 57343, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Private Use Area', 57344, 63743, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('CJK Compatibility Ideographs', 63744, 64255, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Alphabetic Presentation Forms', 64256, 64335, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Arabic Presentation Forms-A', 64336, 65023, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Variation Selectors', 65024, 65039, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Vertical Forms', 65040, 65055, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Combining Half Marks', 65056, 65071, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('CJK Compatibility Forms', 65072, 65103, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Small Form Variants', 65104, 65135, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Arabic Presentation Forms-B', 65136, 65279, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Halfwidth and Fullwidth Forms', 65280, 65519, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Specials', 65520, 65535, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Linear B Syllabary', 65536, 65663, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Linear B Ideograms', 65664, 65791, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Aegean Numbers', 65792, 65855, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Ancient Greek Numbers', 65856, 65935, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Ancient Symbols', 65936, 65999, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Phaistos Disc', 66000, 66047, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Lycian', 66176, 66207, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Carian', 66208, 66271, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Old Italic', 66304, 66351, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Gothic', 66352, 66383, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Ugaritic', 66432, 66463, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Old Persian', 66464, 66527, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Deseret', 66560, 66639, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Shavian', 66640, 66687, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Osmanya', 66688, 66735, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Cypriot Syllabary', 67584, 67647, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Imperial Aramaic', 67648, 67679, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Phoenician', 67840, 67871, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Lydian', 67872, 67903, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Kharoshthi', 68096, 68191, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Old South Arabian', 68192, 68223, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Avestan', 68352, 68415, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Inscriptional Parthian', 68416, 68447, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Inscriptional Pahlavi', 68448, 68479, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Old Turkic', 68608, 68687, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Rumi Numeral Symbols', 69216, 69247, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Kaithi', 69760, 69839, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Cuneiform', 73728, 74751, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Cuneiform Numbers and Punctuation', 74752, 74879, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Egyptian Hieroglyphs', 77824, 78895, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Byzantine Musical Symbols', 118784, 119039, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Musical Symbols', 119040, 119295, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Ancient Greek Musical Notation', 119296, 119375, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Tai Xuan Jing Symbols', 119552, 119647, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Counting Rod Numerals', 119648, 119679, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Mathematical Alphanumeric Symbols', 119808, 120831, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Mahjong Tiles', 126976, 127023, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Domino Tiles', 127024, 127135, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Enclosed Alphanumeric Supplement', 127232, 127487, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Enclosed Ideographic Supplement', 127488, 127743, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('CJK Unified Ideographs Extension B', 131072, 173791, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('CJK Unified Ideographs Extension C', 173824, 177983, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('CJK Compatibility Ideographs Supplement', 194560, 195103, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Tags', 917504, 917631, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Variation Selectors Supplement', 917760, 917999, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Supplementary Private Use Area-A', 983040, 1048575, 'block');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Supplementary Private Use Area-B', 1048576, 1114111, 'block');

INSERT INTO blocks (name, first, last, `type`) VALUES ('Basic Multilingual Plane', 0, 65535, 'plane');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Supplementary Multilingual Plane', 65536, 131071, 'plane');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Supplementary Ideographic Plane', 131072, 196607, 'plane');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Tertiary Ideographic Plane', 196608, 262143, 'plane');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Supplementary Special-purpose Plane', 917504, 983039, 'plane');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Supplementary Private Use Area - A', 983040, 1048575, 'plane');
INSERT INTO blocks (name, first, last, `type`) VALUES ('Supplementary Private Use Area - B', 1048576, 1114111, 'plane');

INSERT INTO blocks (name, first, last, `type`) VALUES ('ASCII', 0, 127, 'special');
